#!/bin/bash

if [ -f ~/.okta-aws ]; then
  sed -i '/app-link = /d' ~/.okta-aws
  sed -i '/role = /d' ~/.okta-aws
fi

if [ -d ~/.aws-okta ]; then
  find ~/.aws-okta -maxdepth 1 -name "*session\ \(*" -type f -delete
fi

pkill -f aws_okta_keyman
