[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"

[BASE]
source = "container"
container = "library/debian"
include_regex = "bookworm-\\d*-slim"

[KUBECTL]
source = "cmd"
cmd = "wget -qO- https://storage.googleapis.com/kubernetes-release/release/stable.txt"
prefix = "v"

[HELM]
source = "github"
github = "helm/helm"
use_max_tag = true
exclude_regex = ".*rc.*|.*alpha.*|.*beta.*"
prefix = "v"

[TERRAFORM]
source = "github"
github = "hashicorp/terraform"
exclude_regex = ".*(alpha|beta|rc\\d|dev).*"
use_max_tag = true
prefix = "v"

[TERRAGRUNT]
source = "github"
github = "gruntwork-io/terragrunt"
use_latest_release = true
prefix = "v"

[PACKER]
source = "github"
github = "hashicorp/packer"
use_latest_release = true
prefix = "v"

[AWS_IAM_AUTH]
source = "github"
github = "kubernetes-sigs/aws-iam-authenticator"
use_latest_release = true
prefix = "v"

[KUBECTX]
source = "github"
github = "ahmetb/kubectx"
use_latest_release = true
prefix = "v"

[KOMPOSE]
source = "github"
github = "kubernetes/kompose"
use_latest_release = true
prefix = "v"

[K9S]
source = "github"
github = "derailed/k9s"
use_latest_release = false
use_max_tag = true
prefix = "v"

[KUBESPY]
source = "github"
github = "pulumi/kubespy"
use_latest_release = false
use_max_tag = true
prefix = "v"

[FLUX2]
source = "github"
github = "fluxcd/flux2"
use_latest_release = true
prefix = "v"

[EKSCTL]
source = "github"
github = "eksctl-io/eksctl"
use_max_tag = true
exclude_regex = ".*rc.*"
prefix = "v"

[CLOUD_NUKE]
source = "github"
github = "gruntwork-io/cloud-nuke"
use_latest_release = true
prefix = "v"

[CONFD]
source = "github"
github = "kelseyhightower/confd"
use_max_tag = true
prefix = "v"

[TERRAFORM_DOCS]
source = "github"
github = "terraform-docs/terraform-docs"
use_latest_release = true
prefix = "v"

[AWS_CLI]
source = "github"
github = "aws/aws-cli"
use_max_tag = true
